# Generated by Django 3.0.5 on 2021-04-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djongo.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawNews',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=200)),
                ('date_time', models.CharField(max_length=255)),
                ('content', djongo.models.fields.JSONField()),
                ('url', models.CharField(max_length=255)),
                ('tags', djongo.models.fields.JSONField()),
                ('section', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('content', djongo.models.fields.JSONField()),
                ('url', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not to Specify', 'Not to Specify')], default='Not to Specify', max_length=15)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('tag', models.ManyToManyField(blank=True, to='taggit.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('news_id', models.CharField(max_length=20, unique=True)),
                ('headline', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=200)),
                ('date_time', models.DateField()),
                ('content', djongo.models.fields.JSONField()),
                ('url', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
